baseURL = ""
languageCode = "en-us"
title = "mitmproxy.org docs"
publishDir = "../public"
RelativeURLs = true
pygmentsCodefences = true
pygmentsUseClasses = true
defaultContentLanguage = "en"

# 多语言支持
[languages]
  [languages.en]
    contentDir = "content"
    languageName = "English"
    weight = 1
  [languages.zh]
    contentDir = "content-zh"
    languageName = "中文"
    weight = 2
    title = "mitmproxy.org 文档"

[indexes]
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[security.funcs]
getenv = ["DOCS_ARCHIVE"]

[outputs]
home = ["HTML", "SEARCHINDEX"]

[mediaTypes]
[mediaTypes."application/javascript"]
suffixes = ["js"]

[outputFormats.SEARCHINDEX]
mediaType = "application/javascript"
baseName = "searchindex"
isPlainText = true
